"use client";
import { useEffect, useState } from "react";

const nav = [["⌂","Dashboard"],["🎬","Movies & Shows"],["🏢","Theatres"],["💺","Screens & Seats"],["🎟","Bookings"],["💳","Payments"],["🍿","POS"],["📦","Inventory"],["🚚","Procurement"],["👥","HR & Attendance"],["🛠","Assets & Maintenance"],["₹","Finance"],["📊","Reports"],["🤖","AI Insights"]];
const stats = [["Today's Revenue","₹0","Connect finance data","revenue"],["Confirmed Bookings","0","Live booking count","bookings"],["Active Shows","0","Scheduled today","shows"],["Low Stock Items","0","Inventory alerts","stock"]];

export default function AdminDashboard(){
 const [api,setApi]=useState("Checking API…"); const [active,setActive]=useState("Dashboard");
 useEffect(()=>{fetch("http://localhost:4000/api/health").then(r=>r.ok?r.json():Promise.reject()).then(()=>setApi("API Online")).catch(()=>setApi("API Offline"));},[]);
 return <div className="admin-app">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">F</div><div><strong>FALCONS</strong><span>SMART THEATRE ERP</span></div></div>
   <div className="nav-label">MAIN MENU</div><nav>{nav.map(([icon,label])=><button key={label} className={active===label?"nav-item active":"nav-item"} onClick={()=>setActive(label)}><span>{icon}</span><span>{label}</span></button>)}</nav>
   <div className="sidebar-bottom"><div className="system-status"><i/> {api}</div><div className="user-mini"><div className="avatar">A</div><div><strong>Administrator</strong><small>Super Admin</small></div></div></div>
  </aside>
  <main className="admin-main"><header className="topbar"><div><div className="crumb">ADMINISTRATION / {active.toUpperCase()}</div><h1>{active}</h1></div><div className="top-actions"><button className="icon-btn">🔔<b>3</b></button><button className="profile-btn"><span className="avatar">A</span><span>Administrator</span><span>⌄</span></button></div></header>
   <section className="welcome"><div><span className="eyebrow">OPERATIONS CONTROL CENTER</span><h2>Good evening, Administrator.</h2><p>Monitor your theatre, bookings, operations and business performance from one workspace.</p></div><div className="date-card"><span>Today</span><strong>{new Date().toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short",year:"numeric"})}</strong></div></section>
   <section className="stat-grid">{stats.map(([title,value,note,key])=><article className="stat-card" key={key}><div className={"stat-icon "+key}>{key==="revenue"?"₹":key==="bookings"?"🎟":key==="shows"?"▶":"!"}</div><div className="stat-content"><span>{title}</span><strong>{value}</strong><small>{note}</small></div></article>)}</section>
   <section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-head"><div><h3>Revenue Overview</h3><p>Paid ticket revenue</p></div><select><option>Last 7 days</option><option>Last 30 days</option><option>This year</option></select></div><div className="chart"><div className="chart-lines"><span>₹50K</span><span>₹40K</span><span>₹30K</span><span>₹20K</span><span>₹10K</span><span>₹0</span></div><div className="chart-bars">{[42,65,48,78,55,88,70].map((h,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:h+"%"}}/><small>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][i]}</small></div>)}</div></div></article>
   <article className="panel"><div className="panel-head"><div><h3>Today's Shows</h3><p>Schedule snapshot</p></div><button className="text-btn">View all →</button></div><div className="show-list">{[["10:30 AM","Morning Show","Screen 01"],["01:45 PM","Afternoon Show","Screen 02"],["05:30 PM","Evening Show","Screen 01"],["09:15 PM","Night Show","Screen 03"]].map(([time,movie,screen])=><div className="show-row" key={time}><strong>{time}</strong><div><b>{movie}</b><small>{screen}</small></div><span className="pill">Scheduled</span></div>)}</div></article></section>
   <section className="dashboard-grid lower"><article className="panel"><div className="panel-head"><div><h3>Recent Bookings</h3><p>Latest customer transactions</p></div><button className="text-btn">View bookings →</button></div><div className="table-wrap"><table><thead><tr><th>Booking</th><th>Customer</th><th>Show</th><th>Amount</th><th>Status</th></tr></thead><tbody>{[["FLC-00124","Customer","Evening Show","₹480","Confirmed"],["FLC-00123","Customer","Afternoon Show","₹360","Confirmed"],["FLC-00122","Customer","Night Show","₹720","Pending"]].map(r=><tr key={r[0]}>{r.map((c,i)=><td key={i} className={i===4?"status "+c.toLowerCase():""}>{c}</td>)}</tr>)}</tbody></table></div></article>
   <article className="panel alerts"><div className="panel-head"><div><h3>Operational Alerts</h3><p>Items requiring attention</p></div></div><div className="alert-row warning"><span>!</span><div><b>Inventory attention</b><small>Review low-stock products.</small></div><button>Open</button></div><div className="alert-row info"><span>i</span><div><b>Maintenance</b><small>Check open maintenance requests.</small></div><button>Open</button></div><div className="alert-row success"><span>✓</span><div><b>System health</b><small>API health endpoint is monitored.</small></div></div></article></section>
  </main>
 </div>;
}