import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../database/prisma.service";
import { randomBytes } from "crypto";
@Injectable()
export class BookingsService {
 constructor(private readonly db:PrismaService){}
 findAll(){return this.db.booking.findMany({include:{show:{include:{movie:true,theatre:true,screen:true}},seats:{include:{seat:true}},payments:true,ticket:true},orderBy:{createdAt:"desc"}})}
 async findOne(id:string){const x=await this.db.booking.findUnique({where:{id},include:{show:{include:{movie:true,theatre:true,screen:true}},seats:{include:{seat:true}},payments:true,ticket:true}});if(!x)throw new NotFoundException("Booking not found");return x}
 async lockSeats(d:any){const token=randomBytes(24).toString("hex");const ttl=Math.min(Math.max(Number(d.ttlMinutes??5),1),15);return this.db.$transaction(async tx=>{const show=await tx.show.findUnique({where:{id:d.showId}});if(!show)throw new NotFoundException("Show not found");await tx.seatLock.deleteMany({where:{showId:d.showId,expiresAt:{lt:new Date()}}});const seats=await tx.seat.findMany({where:{id:{in:d.seatIds},screenId:show.screenId}});if(seats.length!==d.seatIds.length)throw new BadRequestException("Invalid seat selection");const busy=await tx.bookingSeat.findMany({where:{seatId:{in:d.seatIds},booking:{showId:d.showId,status:{in:["PENDING","CONFIRMED","COMPLETED"]}}}});const locked=await tx.seatLock.findMany({where:{showId:d.showId,seatId:{in:d.seatIds}}});if(busy.length||locked.length)throw new BadRequestException("One or more seats are unavailable");const expiresAt=new Date(Date.now()+ttl*60000);await tx.seatLock.createMany({data:d.seatIds.map((seatId:string)=>({showId:d.showId,seatId,token,expiresAt}))});return {token,expiresAt,seatIds:d.seatIds}})}
 async create(d:any){if(!d.seatIds?.length)throw new BadRequestException("At least one seat is required");return this.db.$transaction(async tx=>{const show=await tx.show.findUnique({where:{id:d.showId}});if(!show)throw new NotFoundException("Show not found");await tx.seatLock.deleteMany({where:{expiresAt:{lt:new Date()}}});if(d.lockToken){const locks=await tx.seatLock.findMany({where:{showId:d.showId,token:d.lockToken,seatId:{in:d.seatIds},expiresAt:{gt:new Date()}}});if(locks.length!==d.seatIds.length)throw new BadRequestException("Seat lock expired or invalid")}const seats=await tx.seat.findMany({where:{id:{in:d.seatIds},screenId:show.screenId}});if(seats.length!==d.seatIds.length)throw new BadRequestException("Invalid seat selection");const busy=await tx.bookingSeat.findMany({where:{seatId:{in:d.seatIds},booking:{showId:d.showId,status:{in:["PENDING","CONFIRMED","COMPLETED"]}}}});if(busy.length)throw new BadRequestException("Seat already booked");const bookingCode="FLC-"+Date.now().toString(36).toUpperCase()+"-"+randomBytes(3).toString("hex").toUpperCase();const total=Number(show.basePrice)*seats.length;const booking=await tx.booking.create({data:{bookingCode,showId:d.showId,userId:d.userId,customerName:d.customerName,customerEmail:d.customerEmail,total,status:"PENDING",seats:{create:seats.map(seat=>({seatId:seat.id}))}},include:{show:{include:{movie:true,theatre:true,screen:true}},seats:{include:{seat:true}}}});await tx.seatLock.deleteMany({where:{showId:d.showId,seatId:{in:d.seatIds}}});return booking})}
}